// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    CarouselItem: typeof import('./src/components/CarouselItem.vue')['default']
    EnterCom: typeof import('./src/components/EnterCom.vue')['default']
    EnterS: typeof import('./src/components/EnterS.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    test: typeof import("./src/components/test.vue")["default"];
    Test: typeof import('./src/components/test.vue')['default']
    'Test - 複製': typeof import('./src/components/test - 複製.vue')['default']
    Text: typeof import('./src/components/Text.vue')['default']
    TreeComp: typeof import('./src/components/TreeComp.vue')['default']
    'TreeComp - 複製': typeof import('./src/components/TreeComp - 複製.vue')['default']
    TreeCompEdit: typeof import('./src/components/TreeCompEdit.vue')['default']
    'TreeCompEdit - 複製': typeof import('./src/components/TreeCompEdit - 複製.vue')['default']
    TreeCompView: typeof import('./src/components/TreeCompView.vue')['default']
  }
}

export {}
