// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    EnterCom: typeof import("./src/components/EnterCom.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SecDimensioInput: typeof import("./src/components/SecDimensioInput.vue")["default"];
    TreeCompEdit: typeof import("./src/components/TreeCompEdit.vue")["default"];
    TreeCompView: typeof import("./src/components/TreeCompView.vue")["default"];
  }
}

export {};
